# Generated by Django 2.2 on 2020-03-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_managers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='Managers',
            new_name='Manager',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('allocated_hours', models.IntegerField(null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pro_managers', to='webapp.Manager', verbose_name='project manager')),
            ],
        ),
    ]
