# Generated by Django 2.2 on 2020-03-13 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200313_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_name',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_details', to='webapp.Client', verbose_name='client details'),
        ),
    ]
