# Generated by Django 2.2 on 2020-03-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200313_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
