# Generated by Django 2.2 on 2020-03-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_manager_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
